name: Basic workflow

on: push

jobs:
# Jobs are normally called (build, test)
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: ls -la
      - run: pwd
  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: Step one job 2
        uses: actions/checkout@v4
      - name: Step two job 2
        run: pwd
